title: Marco Sabatini's blog
description: Software crafter.
show_downloads: false
github:
  is_project_page: false
google_analytics:
remote_theme: "jekyll/minima@1e8a445"
permalink: /blog/:year/:month/:day/:title
twitter:
  is_enabled: true
  url: https://twitter.com/marc_sab
