title: Marco Sabatini's blog
description: Software crafter.
show_downloads: false
github:
  is_project_page: false
google_analytics:
theme: jekyll-theme-architect
permalink: /blog/:year/:month/:day/:title
twitter:
  isEnabled: true
  url: https://twitter.com/marc_sab