title: Marco Sabatini's blog
description: Software crafter.
github:
  is_project_page: false
show_downloads: false # theme setting, hide download links if supported
google_analytics:
theme: jekyll-theme-hacker
